In [80]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plts
import math
from sklearn.datasets import load_iris
from __future__ import division

iris = load_iris()

log = math.log(4, 2)



In [81]:
def entropy(classes):
    rows = np.sum(classes)
    entropy = 0
    for i in classes:
        if(i != 0):
            entropy = entropy - (i/rows)*(np.log2((i)/rows))
            
    return entropy

def max_gain(uniques, classes):
    infg = []
    for i in range(len(uniques)):
        g = entropy(classes[1])
        for j in range(len(uniques[i][0])):
            g = g - (uniques[i][1][j]/(np.sum(uniques[i][1])))*entropy([uniques[i][2+k][j] for k in range(len(classes[0][0]))])
        infg.append(g)
    return infg.index(max(infg))

In [143]:
class node:
    
    def __init__(self, data, index):
        self.nodes = []
        self.data = data
        self.index = index
        self.isleaf = False
        self.leafdata = ""
        
    



In [176]:
class dtreeclassifier:
        
    def entropy(self, classes):
        rows = np.sum(classes)
        entropy = 0
        for i in classes:
            if(i != 0):
                entropy = entropy - (i/rows)*(np.log2((i)/rows))

        return entropy

    def max_gain(self, uniques, classes):
        infg = []
        for i in range(len(uniques)):
            g = self.entropy(classes[1])
            for j in range(len(uniques[i][0])):
                g = g - (uniques[i][1][j]/(np.sum(uniques[i][1])))*self.entropy([uniques[i][2+k][j] for k in range(len(classes[0][0]))])
            infg.append(g)
        return infg.index(max(infg))
    
    
    def unique(self, X, y):
        uniques = []
        for i in range(X.shape[1]):
            uniques.append(list(np.unique(X[:, i], return_counts=True)))
            for j in range(len(classes[0])):
                uniques[i].append(np.zeros(len(uniques[i][0])))


        for i in range(len(uniques)):
            for j in range(X.shape[0]):
                clas = np.where(classes[0] == (y[j]))
                uniques[i][clas[0][0]+2][np.where(uniques[i][0] == (X[j][i]))[0][0]] += 1
                
        return uniques
    
    def recursion(self, root, X, y):
        if(root.isleaf == False):
                uniques = self.unique(X, y)
                classes = np.unique(y)
                print(root.isleaf)
                max_index = self.max_gain(uniques, classes)
                
                for i in range(len(uniques[max_index][0])):
                    root.nodes.append(node(uniques[max_index][0][i], max_index), max_index)
                    for j in range(len(classes[0])):
                        if(uniques[max_index][2+j][i] == 0):
                            root.nodes[-1].isleaf = True
                            root.nodes[-1].leafdata = classes[0][1]
                    recursion(self, root.nodes[-1], X[X[:, root.index] == root.data], y[X[:, root.index] == root.data])
    
    def fit(self, X, y, typ, depth = 5):
        print("Fitted" + " depth is " + str(depth))
        
        if(typ == 1):            # continous and continous
            print("do this")
            
        elif(typ == 2):         # continous and discrete
            print("do this")
        
        elif(typ == 3):         # discrete and discrete
            
            classes = np.unique(y, return_counts=True)
            uniques = self.unique(X, y)



            print(self.max_gain(uniques, classes))
            
            
            max_index = self.max_gain(uniques, classes)
            
            
            root = node(max_index, max_index)
            
            for i in range(len(uniques[max_index][0])):
                root.nodes.append(node(uniques[max_index][0][i], max_index))
                for j in range(len(classes[0])):
                    if(uniques[max_index][2+j][i] == 0):
                        root.nodes[-1].isleaf = True
                        root.nodes[-1].leafdata = classes[0][1]
                self.recursion(root.nodes[-1], X[X[:, root.index] == root.data], y[X[:, root.index] == root.data])
            
                
            return root 
            
            print("do this")
        
        elif(typ == 4):         # discrete and continous
            print("error in input")
            
        else:
            print("Error in inputs")
        
    def predict(self, X_test):
        print("Predicted")
        
    def accuracy(self, X_test, y_test):
        print("accuracy is x%")
        
    
        

In [177]:
tree = dtreeclassifier()

In [178]:
a = tree.fit(X, y, 3)
tree.predict(y)
tree.accuracy(X, y)
entropy(classes[1])
a.nodes[1].leafdata



Fitted depth is 5
0
False


/home/gowtham/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:84: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison


IndexError: index 1 is out of bounds for axis 0 with size 0

In [182]:
a.index

AttributeError: node instance has no attribute 'index'

In [453]:
iris.target[10:56], len(iris.target)

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
        1, 1]), 150)

In [454]:
X = iris.data
y = iris.target
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [455]:
X_train[:5], y_train[:5]

(array([[5. , 3.5, 1.3, 0.3],
        [5. , 3.3, 1.4, 0.2],
        [6.3, 2.8, 5.1, 1.5],
        [6.7, 3.3, 5.7, 2.1],
        [7.3, 2.9, 6.3, 1.8]]), array([0, 0, 2, 2, 2]))

In [456]:
data = open("tennis.csv", 'r')
dataset = []
for i in data.readlines():
    dataset.append(i.rstrip().split(','))

    
data = pd.read_csv('tennis.csv')

In [457]:
X = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

In [458]:
X, y

(array([['sunny', 'hot', 'high', False],
        ['sunny', 'hot', 'high', True],
        ['overcast', 'hot', 'high', False],
        ['rainy', 'mild', 'high', False],
        ['rainy', 'cool', 'normal', False],
        ['rainy', 'cool', 'normal', True],
        ['overcast', 'cool', 'normal', True],
        ['sunny', 'mild', 'high', False],
        ['sunny', 'cool', 'normal', False],
        ['rainy', 'mild', 'normal', False],
        ['sunny', 'mild', 'normal', True],
        ['overcast', 'mild', 'high', True],
        ['overcast', 'hot', 'normal', False],
        ['rainy', 'mild', 'high', True]], dtype=object),
 array(['no', 'no', 'yes', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'yes',
        'yes', 'yes', 'yes', 'no'], dtype=object))

In [460]:
attrs, pos, neg

(array(['overcast', 'rainy', 'sunny'], dtype=object),
 array([2., 2., 2.]),
 array([2., 3., 3.]))

In [109]:
string = "Day Outlook Temp Humidity Wind PlayTennis\nD1 Sunny Hot High Weak No\nD2 Sunny Hot High Strong No\nD3 Overcast Hot High Weak Yes\nD4 Rain Mild High Weak Yes\nD5 Rain Cool Normal Weak Yes\nD6 Rain Cool Normal Strong No\nD7 Overcast Cool Normal Strong Yes\nD8 Sunny Mild High Weak No\nD9 Sunny Cool Normal Weak Yes\nD10 Rain Mild Normal Weak Yes\nD11 Sunny Mild High Strong Yes\nD12 Overcast Mild High Strong Yes\nD13 Overcast Hot Normal Weak Yes\nD14 Rain Mild High Strong No"

In [110]:
string = string.split('\n')
data = []
for i in string:
    data.append(i.split(' '))

In [111]:
data = np.array(data)
data
X = data[1:, 1:-1]
y = data[1:, -1]

In [112]:
classes = np.unique(y, return_counts=True)
classes

(array(['No', 'Yes'], dtype='|S10'), array([5, 9]))

In [113]:
uniques = []
for i in range(X.shape[1]):
    uniques.append(list(np.unique(X[:, i], return_counts=True)))
    for j in range(len(classes[0])):
        uniques[i].append(np.zeros(len(uniques[i][0])))

In [114]:
uniques

[[array(['Overcast', 'Rain', 'Sunny'], dtype='|S10'),
  array([4, 5, 5]),
  array([0., 0., 0.]),
  array([0., 0., 0.])],
 [array(['Cool', 'Hot', 'Mild'], dtype='|S10'),
  array([4, 4, 6]),
  array([0., 0., 0.]),
  array([0., 0., 0.])],
 [array(['High', 'Normal'], dtype='|S10'),
  array([8, 6]),
  array([0., 0.]),
  array([0., 0.])],
 [array(['Strong', 'Weak'], dtype='|S10'),
  array([6, 8]),
  array([0., 0.]),
  array([0., 0.])]]

In [115]:
def entropy(classes):
    rows = np.sum(classes)
    print rows
    entropy = 0
    for i in classes:
        if(i != 0):
            entropy = entropy - (i/rows)*(np.log2((i)/rows))
            
    return entropy

In [116]:
a = entropy(classes[1])
a

14


0.9402859586706309

In [117]:
uniques[0]

[array(['Overcast', 'Rain', 'Sunny'], dtype='|S10'),
 array([4, 5, 5]),
 array([0., 0., 0.]),
 array([0., 0., 0.])]

In [118]:
for i in range(len(uniques)):
    for j in range(X.shape[0]):
        clas = np.where(classes[0] == (y[j]))
        uniques[i][clas[0][0]+2][np.where(uniques[i][0] == (X[j][i]))[0][0]] += 1

In [119]:
uniques

[[array(['Overcast', 'Rain', 'Sunny'], dtype='|S10'),
  array([4, 5, 5]),
  array([0., 2., 3.]),
  array([4., 3., 2.])],
 [array(['Cool', 'Hot', 'Mild'], dtype='|S10'),
  array([4, 4, 6]),
  array([1., 2., 2.]),
  array([3., 2., 4.])],
 [array(['High', 'Normal'], dtype='|S10'),
  array([8, 6]),
  array([4., 1.]),
  array([4., 5.])],
 [array(['Strong', 'Weak'], dtype='|S10'),
  array([6, 8]),
  array([3., 2.]),
  array([3., 6.])]]

In [508]:
def max_gain(uniques, classes):
    infg = []
    for i in range(len(uniques)):
        g = entropy(classes[0])
        for j in range(len(uniques[i][0])):
            g = g - (uniques[i][1][j]/(np.sum(uniques[i][1])))*entropy([uniques[i][2+k][j] for k in range(len(classes[0][0]))])
        infg.append(g)
    return infg.index(max(infg))

In [509]:
max_gain(uniques, classes)

20.0
25.0
25.0
20.0
20.0
30.0
40.0
30.0
30.0
40.0


0

In [134]:
X

array([['Sunny', 'Hot', 'High', 'Weak'],
       ['Sunny', 'Hot', 'High', 'Strong'],
       ['Overcast', 'Hot', 'High', 'Weak'],
       ['Rain', 'Mild', 'High', 'Weak'],
       ['Rain', 'Cool', 'Normal', 'Weak'],
       ['Rain', 'Cool', 'Normal', 'Strong'],
       ['Overcast', 'Cool', 'Normal', 'Strong'],
       ['Sunny', 'Mild', 'High', 'Weak'],
       ['Sunny', 'Cool', 'Normal', 'Weak'],
       ['Rain', 'Mild', 'Normal', 'Weak'],
       ['Sunny', 'Mild', 'High', 'Strong'],
       ['Overcast', 'Mild', 'High', 'Strong'],
       ['Overcast', 'Hot', 'Normal', 'Weak'],
       ['Rain', 'Mild', 'High', 'Strong']], dtype='|S10')

In [135]:
y

array(['No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes',
       'Yes', 'Yes', 'Yes', 'No'], dtype='|S10')

In [138]:
y[X[:, 0] == 'Sunny']

array(['No', 'No', 'No', 'Yes', 'Yes'], dtype='|S10')