In [29]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [30]:
X = np.array([1, 2, 2, 4, 3, 6, 4, 8]).reshape([4, 2])
y = np.array([2, 3, 4, 5]).reshape([4, 1])

In [31]:
X

array([[1, 2],
       [2, 4],
       [3, 6],
       [4, 8]])

In [32]:
y

array([[2],
       [3],
       [4],
       [5]])

In [33]:
from sklearn.linear_model import Ridge
clf = Ridge(1e-3)
clf.fit(X, y)

Ridge(alpha=0.001, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001)

In [34]:
print(clf.coef_, clf.intercept_)

[[0.199992 0.399984]] [1.0001]


In [35]:
def normalEquationRidgeRegression(X, y, alpha):
    one = np.ones(X.shape[0]).reshape([-1, 1])
    X = np.concatenate((one, X), axis = 1)
    XXT = np.matmul(np.transpose(X), X)
    XXTY = np.matmul(np.linalg.inv(XXT+alpha*np.identity(X.shape[1])), np.transpose(X))
    reg = np.matmul(XXTY, y)
    return reg

In [36]:
clf = normalEquationRidgeRegression(X, y, 1)

In [37]:
clf

array([[0.44705882],
       [0.23529412],
       [0.47058824]])